name: deploy-dab

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: be945e7a-2e17-4b44-926f-512e85873eec
          subscription-id: 6a3bb170-5159-4bff-860b-aa74fb762697

      - name: Build image in ACR
        shell: bash
        run: |
          az acr build \
            --registry "acrvpdabdemo" \
            --resource-group "rg-vp-dabdemo" \
            --image "vkp-dab-api:${GITHUB_SHA}" \
            ./dab

      - name: Update Container App
        shell: bash
        run: |
          ACR_LOGIN_SERVER=$(az acr show \
            --name "acrvpdabdemo" \
            --resource-group "rg-vp-dabdemo" \
            --query "loginServer" \
            --output tsv)

          UAMI_CLIENT_ID=$(az identity show \
            --name "id-vp-aca-dabdemo" \
            --resource-group "rg-vp-dabdemo" \
            --query "clientId" \
            --output tsv)

          az containerapp update \
            --name "ca-vp-dabdemo" \
            --resource-group "rg-vp-dabdemo" \
            --image "${ACR_LOGIN_SERVER}/vkp-dab-api:${GITHUB_SHA}" \
            --set-env-vars "AZURE_CLIENT_ID=${UAMI_CLIENT_ID}"
